apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xzdijv5de-go 
  janus-idp.io/tekton: xzdijv5de-go
  backstage.io/kubernetes-id: xzdijv5de-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xzdijv5de-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml